"""add notifications and system_health_logs tables, sensor_data battery and signal fields

Revision ID: 4453ae45ec20
Revises: e1f2a3b4c5d6
Create Date: 2026-06-16 16:45:00.774677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4453ae45ec20'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_health_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('info', 'warning', 'critical', 'success', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_helmet_id', sa.UUID(), nullable=True),
    sa.Column('related_alert_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['related_helmet_id'], ['helmets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sensor_data', sa.Column('battery_level', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('signal_strength', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'signal_strength')
    op.drop_column('sensor_data', 'battery_level')
    op.drop_table('notifications')
    op.drop_table('system_health_logs')
    # ### end Alembic commands ###
