"""initial

Revision ID: 500ec7fd7048
Revises: 1a7a04557454
Create Date: 2026-06-02 16:47:28.048890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500ec7fd7048'
down_revision: Union[str, Sequence[str], None] = '1a7a04557454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_gateways',
    sa.Column('supervisor_id', sa.UUID(), nullable=False),
    sa.Column('gateway_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ),
    sa.PrimaryKeyConstraint('supervisor_id', 'gateway_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supervisor_gateways')
    # ### end Alembic commands ###
